my hw jv-dependency-injection
mate-academy/jv-dependency-injection pull request #350
Opened 2022-09-04 11:04 UTC by fifahater

2022-09-04 11:26 UTC, valentyn-chepiha requested changes
Good job

2022-09-04 11:26 UTC, valentyn-chepiha commented on src/main/java/mate.academy/lib/Injector.java
> +                 | IllegalAccessException e) {
```suggestion
        } catch (ReflectiveOperationException e) {
```

2022-09-04 12:02 UTC, valentyn-chepiha approved these changes

2022-09-05 06:51 UTC, Noct2000 requested changes

2022-09-05 06:51 UTC, Noct2000 commented on src/main/java/mate.academy/lib/Injector.java
> +                    throw new RuntimeException("Can't initialize filed value. "
add root cause exception

2022-09-05 07:59 UTC, Noct2000 requested changes

2022-09-05 07:59 UTC, Noct2000 commented on src/main/java/mate.academy/lib/Injector.java
> +                    + interfaceClazz.getName());
```suggestion
                    + clazz.getName());
```

2022-09-05 08:25 UTC, Noct2000 approved these changes

2024-09-17 20:22 UTC, closed without merging