Dependency injection was implemented
mate-academy/jv-dependency-injection pull request #378
Opened 2022-09-06 14:24 UTC by not4und

2022-09-06 18:37 UTC, zachar-chorny requested changes

2022-09-06 18:37 UTC, zachar-chorny commented on src/main/java/mate.academy/lib/Component.java
> +@Target(ElementType.TYPE)
This annotation is not necessary here

2022-09-06 18:37 UTC, zachar-chorny commented on src/main/java/mate.academy/lib/Inject.java
> +@Target(ElementType.FIELD)
same

2022-09-06 18:37 UTC, zachar-chorny commented on src/main/java/mate.academy/lib/Injector.java
> +                 | InstantiationException | IllegalAccessException e) {
<img width="1013" alt="Screen Shot 2022-09-06 at 9 35 20 PM" src="https://user-images.githubusercontent.com/90692308/188712868-663283cb-60ff-458f-9580-ecd26435f330.png">
Read the checklist carefully, the mentor may not check the job further if it has errors listed in the checklist

2022-09-07 14:44 UTC, kozhukhovsky approved these changes

2023-05-08 06:57 UTC, closed without merging