Made dependency injection for project logic. Added implementation for…
mate-academy/jv-dependency-injection pull request #701
Opened 2023-08-04 09:01 UTC by Denis-Balako

… Component and Inject annotations, Injector.

2023-08-04 12:57 UTC, holsoni requested changes
Nice solution, one small comment

2023-08-04 12:57 UTC, holsoni commented on src/main/java/mate.academy/lib/Injector.java
> +        }
I think that you have to check if Class has Component Annotation not when creating an instance of class, but in the very beginning of your getInstance() method. Why do you need to do all of this operations, if the class doesn't  has this annotation?

2023-08-04 13:13 UTC, holsoni approved these changes

2023-08-08 09:33 UTC, Vasul-Pankiv approved these changes

2023-08-08 09:33 UTC, Vasul-Pankiv commented on src/main/java/mate.academy/lib/Component.java
> +@Target(value = {ElementType.TYPE})
```suggestion
@Target(ElementType.TYPE)
```

2026-05-02 16:41 UTC, closed without merging