implemented injector
mate-academy/jv-dependency-injection pull request #707
Opened 2023-08-07 17:45 UTC by IvanFadieiev

2023-08-07 19:34 UTC, keda-vlad requested changes

2023-08-07 19:34 UTC, keda-vlad commented on src/main/java/mate.academy/service/FileReaderService.java
> +@Component
U don't need annotation here, only on implementation
"Convention is to use @Component on the classes that are used for instance creation (usually these are interface implementations) "

2023-08-07 19:34 UTC, keda-vlad commented on src/main/java/mate.academy/service/ProductParser.java
>  public interface ProductParser {
same

2023-08-07 19:34 UTC, keda-vlad commented on src/main/java/mate.academy/service/ProductService.java
>  public interface ProductService {
same

2023-08-08 11:45 UTC, vovasalyha approved these changes
Please see the comment.

2023-08-08 11:45 UTC, vovasalyha commented on src/main/java/mate.academy/lib/Injector.java
> +        if (clazz.isAnnotationPresent(Component.class)) {
It's better to check in if statement if annotation is absent and throw exception if true (better even create a separate method to check it). It'll make your code cleaner.

2023-08-08 18:51 UTC, keda-vlad approved these changes

2026-07-11 10:05 UTC, closed without merging