Create injector functions
mate-academy/jv-dependency-injection pull request #712
Opened 2023-08-08 11:40 UTC by ConfusedSatlan

2023-08-08 11:59 UTC, Someboty requested changes
Great work! Let's finish it)

2023-08-08 11:59 UTC, Someboty commented on src/main/java/mate.academy/service/ProductParser.java
> +@Component
Same here

2023-08-08 11:59 UTC, Someboty commented on src/main/java/mate.academy/service/ProductService.java
> +@Component
And here

2023-08-08 11:59 UTC, Someboty commented on src/main/java/mate.academy/service/FileReaderService.java
> +@Component
Why do you need @Component both on the interface and its implementation?

2023-08-08 11:59 UTC, Someboty commented on src/main/java/mate.academy/lib/Injector.java
> +                 | IllegalAccessException e) {
It is better to replace many exceptions that have a common parent with a general parental exception.

Bad example: 
} catch (InvocationTargetException | InstantiationException
      | IllegalAccessException | NoSuchMethodException e) {

Good example: 
} catch (ReflectiveOperationException e) {

2023-08-08 11:59 UTC, Someboty commented on src/main/java/mate.academy/lib/Injector.java
> +        instances = new HashMap<>();
I don't sure you need it in the constructor

2023-08-08 12:43 UTC, vovasalyha requested changes

2023-08-08 12:43 UTC, vovasalyha commented on src/main/java/mate.academy/lib/Injector.java
> +        injector = new Injector();
Initialize it immediately during declaration, it's not necessary to do it here, same with map of implementations.

2023-08-08 12:43 UTC, vovasalyha commented on src/main/java/mate.academy/lib/Injector.java
> +            throw new RuntimeException("Class must be annotated with @Component");
The message is not informative, specify which class is not annotated. Also it's better to extract this check to separate method to make this method less complex.

2023-08-08 12:48 UTC, Someboty requested changes
Great! Added some more suggestions to improve your solution)

2023-08-08 12:48 UTC, Someboty commented on src/main/java/mate.academy/lib/Injector.java
> +        }
You can add it to the findImplementation() method or create a new one.

2023-08-08 12:48 UTC, Someboty commented on src/main/java/mate.academy/lib/Injector.java
> +            throw new RuntimeException("Can't create a new instance" + clazz.getName());
When you throw an exception add an informative message to it. Also, don’t forget to add an exception you’re catching in the catch block to the RuntimeException object you throw

Bad example: 
} catch(Exception e) {
throw new SomeException("Can't initialize object with Injector");
}
Good example: 
} catch(Exception e) {
throw new SomeException("Injection failed, missing @Component annotaion on the class " + someInfoAboutClass, e);
}

2023-08-08 12:48 UTC, Someboty commented on src/main/java/mate.academy/lib/Injector.java
> +        injector = new Injector();
Do you really need this block? You can use Map.of() and create a new Injector directly in the fields

2023-08-09 08:46 UTC, nacenik approved these changes
LGTM! 👍

2024-04-22 11:08 UTC, closed without merging