Injector implementation created using Component annotation
mate-academy/jv-dependency-injection pull request #844
Opened 2023-12-13 11:30 UTC by ivanlavrinenko

2023-12-13 13:18 UTC, okuzan requested changes

2023-12-13 13:18 UTC, okuzan commented on src/main/java/mate.academy/lib/Component.java
> +@Retention(RetentionPolicy.RUNTIME)
add @Target
Make sure to avoid these mistakes
https://github.com/mate-academy/jv-dependency-injection/blob/main/checklist.md

2023-12-13 13:19 UTC, okuzan commented on src/main/java/mate.academy/lib/Injector.java
> +        interfaceImplementationsMap.put(ProductParser.class, ProductParserImpl.class);
Use map.of , make it a class field

2023-12-14 12:40 UTC, kozhukhovsky approved these changes

2024-12-20 03:07 UTC, closed without merging